# Generated by Django 2.2 on 2019-04-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artistsell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('princesum', models.IntegerField()),
                ('service_type', models.CharField(max_length=50)),
                ('sell_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
